
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#sensor: !include sensors.yaml
input_number: !include input_numbers.yaml

python_script:
  requirements:
    - paramiko>=2.7.1
    - icalendar
    - datetime
    - pytz
    - os
    - asyncio
    - requests

logger:
  default: info
  logs:
    custom_components.pyscript: debug

template:
  - sensor:
      - name: "Saal Solltemperatur"
        unique_id: sensor.saal_solltemperatur
        unit_of_measurement: "°C"
        state: >
          {% if is_state('input_boolean.manueller_modus_saal', 'on') %}
            {{ states('input_number.saal_manuell') | float(0) }}
          {% else %}
            {% set m = states('input_select.saal_modus') %}
            {% if m == 'Heizen' %}
              {{ states('input_number.saal_heizen') | float(0) }}
            {% elif m == 'Sparen' %}
              {{ states('input_number.saal_sparen') | float(0) }}
            {% else %}
              {{ states('input_number.saal_frost') | float(0) }}
            {% endif %}
          {% endif %}

  - sensor:
      - name: "Gaststube Solltemperatur"
        unique_id: sensor.gaststube_solltemperatur
        state: >
          {% if is_state('input_boolean.manueller_modus_gaststube', 'on') %}
            {{ states('input_number.gaststube_manuell') | float(0) }}
          {% else %}
            {% set m = states('input_select.gaststube_modus') %}
            {% if m == 'Heizen' %}
              {{ states('input_number.gaststube_heizen') }}
            {% elif m == 'Sparen' %}
              {{ states('input_number.gaststube_sparen') }}
            {% else %}
              {{ states('input_number.gaststube_frost') }}
            {% endif %}
          {% endif %}

  - sensor:
      - name: "Gaststube Heizbedarf berechnet"
        unique_id: sensor.gaststube_heizbedarf_berechnet
        state: "{{ states('sensor.gaststube_solltemperatur')|float - states('sensor.durchschnitt_gaststube_helfer')|float }}"
  - sensor:
      - name: "Saal Heizbedarf berechnet"
        unique_id: sensor.saal_heizbedarf_berechnet
        state: "{{ states('sensor.saal_solltemperatur')|float - states('sensor.durchschnitt_saal_helfer')|float }}"

  - sensor:
      - name: "Heizbedarf Hoeherer Wert"
        unique_id: sensor.heizbedarf_hoeherer_wert
        unit_of_measurement: ""
        state: >
          {% set a = states('sensor.gaststube_heizbedarf_berechnet') | float(0) %}
          {% set b = states('sensor.saal_heizbedarf_berechnet') | float(0) %}
          {{ [0, a, b] | max }}

  #############################################
  # SOLL-VORLAUFTEMPERATUR (PID + Wetter)     #
  #############################################

  - sensor:
      - name: "Therme Soll-Vorlauftemperatur"
        unique_id: sensor.soll_vorlauf_temperatur
        unit_of_measurement: "°C"
        state: >
          {% set aussentemp = states('sensor.aussentemperatursensor_temperatur') | float(0) %}
          {% set heizbedarf = states('sensor.heizbedarf_hoeherer_wert') | float(0) %}

          {% if heizbedarf == 0 %}
            0
          {% else %}
            {% set gewicht = heizbedarf / 5 %}
            {% set vl =
               35
               + (20 - aussentemp) * 1.2 * gewicht
               + heizbedarf * 5
            %}
            {{ [75, [50, vl] | max ] | min | round(1) }}
          {% endif %}

  #  - sensor:
  #      - name: "Therme Soll-Vorlauftemperatur"
  #        unique_id: sensor.soll_vorlauf_temperatur
  #        unit_of_measurement: "°C"
  #        state: >
  #          {% set ta = states('sensor.aussentemperatursensor_temperatur') | float(0) %}
  #
  #          {% set hb = states('sensor.heizbedarf_hoeherer_wert') | float(0) %}
  #
  #          {% set m = -1.5 %}
  #
  #          {% set tb = 55 + hb %}
  #
  #          {% if hb == 0 %}
  #            0
  #          {% else %}
  #            {% set tv = (m * ta + tb) | round(1) %}
  #
  #            {{ [70, [50, tv] | max ] | min | round(1) }}
  #          {% endif %}

  #####################################################
  # Werte für Solltemperatur High und low berechnen   #
  #####################################################

  - sensor:
      - name: "Therme Zieltemperatur low"
        unique_id: sensor.therme_target_temp_low
        unit_of_measurement: "°C"
        state: >
          {{ states('sensor.therme_soll_vorlauftemperatur')|float(50) - 7 }}
      - name: "Therme Zieltemperatur high"
        unique_id: sensor.therme_target_temp_high
        unit_of_measurement: "°C"
        state: >
          {{ states('sensor.therme_soll_vorlauftemperatur')|float(50) + 7 }}




input_select:
  saal_modus:
    name: Modus Saal
    options: ["Frostschutz", "Sparen", "Heizen"]
  gaststube_modus:
    name: Modus Gaststube
    options: ["Frostschutz", "Sparen", "Heizen"]
  saal_timer_dauer:
    options:
      - "15"
      - "30"
      - "60"

notify:
  - platform: smtp
    name: gmail
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: mark.breitenbuecher@gmail.com
    sender_name: "Home Assistant Alert"
    encryption: starttls
    username: mark.breitenbuecher@gmail.com
    password: !secret max_gmail_password
    recipient:
      - breitenbuechermax@gmail.com
      - mark.breitenbuecher@gmail.com

climate:
  - platform: generic_thermostat
    name: Vorlaufregelung PID
    heater: switch.fake_heater  # Dummy
    target_sensor: sensor.soll_vorlauf_temperatur
    min_temp: 20
    max_temp: 80
    ac_mode: false
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    initial_hvac_mode: "heat"

input_boolean:
  manueller_modus_therme:
    name: Manueller Modus Therme
    icon: mdi:hand
  manueller_modus_saal:
    name: Manueller Modus Saal
    icon: mdi:hand
  manueller_modus_gaststube:
    name: Manueller Modus Gaststube
    icon: mdi:hand

timer:
  saal_timer_manueller_modus:
    name: Saal Timer Manueller Modus
    duration: "01:00:00"

  gaststube_timer_manueller_modus:
    name: Gaststube Timer Manueller Modus
    duration: "01:00:00"




