#see documentation: https://esphome.io
substitutions:
  unit_name: "smarttherm"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

    - ssid: !secret wifi_ssid_max
      password: !secret wifi_password_max

    - ssid: ${unit_name} Fallback Hotspot
      password: !secret fallback_password
  #  fast_connect: true
  reboot_timeout: 0s

esphome:
  name: ${unit_name}

esp8266:
  board: d1_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


captive_portal:

# 1-Wire Bus für Dallas Sensoren auf GPIO0
one_wire:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT

sensor:
  - platform: dallas_temp
    address: 0x74106f7c0a646128
    id: junkers_vorlauf
    name: "junkers_vorlauf"
    update_interval: 10s
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-plus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
  - platform: dallas_temp
    address: 0x6b5103710a646128
    id: junkers_ruecklauf
    name: "junkers_ruecklauf"
    update_interval: 10s
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-minus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2


# PWM Output auf GPIO15 (0.1=aus, 0.2=an)
output:
  - platform: esp8266_pwm
    pin: GPIO15
    id: pwm_heizung
    frequency: 1000Hz

# Bang-Bang Climate Controller (Zweipunktregler)
climate:
  - platform: bang_bang
    name: "Heizungs Thermostat"
    sensor: junkers_vorlauf
    default_target_temperature_low: 50.0°C
    default_target_temperature_high: 60.0°C  # 1K Hysterese
    heat_action:
      - output.set_level:
          id: pwm_heizung
          level: 0.3
    idle_action:
      - output.set_level:
          id: pwm_heizung
          level: 0.01
    visual:
      min_temperature: 30°C
      max_temperature: 80°C
      temperature_step: 0.5°C
