#see documentation: https://esphome.io
substitutions:
  unit_name: "smarttherm"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

    - ssid: !secret wifi_ssid_max
      password: !secret wifi_password_max

    - ssid: ${unit_name} Fallback Hotspot
      password: !secret fallback_password
  #  fast_connect: true
  reboot_timeout: 0s

esphome:
  name: ${unit_name}
  on_boot:
    priority: -100 # after everything is initialized
    then:
      - script.execute: update_pwm_level

esp8266:
  #  board: esp01_1m
  board: d1_mini


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password


captive_portal:

output:
  - platform: esp8266_pwm
    pin: #D8 # octocopler drive
      number: GPIO15
    frequency: 1000 Hz # default
    id: pwm_output

switch:
  - platform: template
    name: ${unit_name}_heating
    id: heating
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    icon: "mdi:water-boiler"
    optimistic: True
    turn_on_action:
      - light.turn_on: onboard_led
      - script.execute: set_pwm_level_from_slider
    turn_off_action:
      - light.turn_off: onboard_led
      - script.execute: set_pwm_low_level

light:
  - platform: status_led
    id: onboard_led
    internal: True
    pin:
      number: GPIO2
      inverted: true

script:
  - id: set_pwm_level_from_slider
    then:
      - lambda: |-
          id(pwm_output).set_level(id(pwm_output_level).state);

  - id: set_pwm_low_level
    then:
      - lambda: |-
          id(pwm_output).set_level(0.07);// ~5v off

  - id: update_pwm_level
    then:
      - lambda: |-
          if (id(heating).state) {
            id(set_pwm_level_from_slider).execute();
          } else {
            id(set_pwm_low_level).execute();
          }

number:
  # power slider in percent for home assistant
  - platform: template
    name: ${unit_name}_power_level
    id: power_level
    restore_value: True
    step: 1
    min_value: 1
    max_value: 100
    unit_of_measurement: "%"
    mode: slider
    optimistic: True
    entity_category: config
    icon: "mdi:gas-burner"
    on_value:
      then:
        - sensor.template.publish:
            id: pwm_output_level
            state: !lambda "return x;"



one_wire:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT

sensor:
  - platform: dallas_temp
    address: 0x74106f7c0a646128
    name: "dallas_vorlauf"
    update_interval: 10s
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-plus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
  - platform: dallas_temp
    address: 0x6b5103710a646128
    name: "dallas_ruecklauf"
    update_interval: 10s
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-minus"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2

  # map percent slider value to float level of pwm output
  # based on http://www.roter-unimog.de/p4/46-hzg-technik.htm
  - platform: template
    id: pwm_output_level
    internal: True
    lambda: |-
      return id(power_level).state;
    filters:
      # measure voltage and adjust for your device
      - calibrate_linear:
          # - 1 -> 0.09 # ~5,4v min
          - 1 -> 0.10 # ~5,8v
          - 100.0 -> 0.70 # ~15v max
          # Original:- 100.0 -> 0.70 # ~15v max
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "pwm ouput level: %.2f"
            args: ['x']
        - script.execute: update_pwm_level
